config/routes.rb
Rails.application.routes.draw do

  resources :cats
  resources :cat_rental_requests do
    post "approve", on: :member
    post "deny", on: :member
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

end

app/models/cat.rb
class Cat < ActiveRecord::Base

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates_inclusion_of :sex, in: ["M", "F"]

  def age
    (Date.today - birth_date).to_i / 365
  end

  def self.colors
    ["blue", "orange", "black", "brown", "white"]
  end

  has_many(
    :rental_requests,
    class_name: 'CatRentalRequest',
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
  )

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates_inclusion_of :status, in: ["PENDING", "APPROVED", "DENIED"]
  validate :no_overlapping_requests


  belongs_to(
    :cat,
    class_name: "Cat",
    foreign_key: :cat_id,
    primary_key: :id
  )

  def overlapping_requests

    CatRentalRequest
      .select("*")
      .where(
        "cat_id = ? AND
        id != ? AND NOT

          ( ? < start_date OR
          end_date < ? )
        ", cat_id, id, end_date, start_date
      )

    # CatRentalRequest.select do |request|
    #   request.cat_id == cat_id &&
    #   request.id != id &&
    #   !(end_date < request.start_date || request.end_date < start_date)
    # end
  end

  def approve!
    raise "not pending" unless self.status == "PENDING"
    transaction do
      self.status = "APPROVED"
      self.save!

      # when we approve this request, we reject all other overlapping
      # requests for this cat.
      overlapping_pending_requests.update_all(status: 'DENIED')
    end
  end

  def approved?
    self.status == "APPROVED"
  end

  def denied?
    self.status == "DENIED"
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def pending?
    self.status == "PENDING"
  end

  private
  def assign_pending_status
    self.status ||= "PENDING"
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = 'PENDING'")
  end

    def no_overlapping_requests
      errors[:base] << "This cat is already rented out" unless overlapping_approved_requests.empty?
    end
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :user_name, :password_digest, :session_token, presence: true
  validates :session_token, uniqueness: true
  validates :password, length: { minimum: 6 }

  def self.generate_session_token
    token = SecureRandom.urlsafe_base64
    while User.exists?(session_token: token)
      token = SecureRandom.urlsafe_base64
    end
    token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
  end

  def password
    @password
  end

  def password=(new_password)
    # @password = BCrypt::Password.create(new_password)
    # self.password_digest = @password
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def is_password?(input_pass)
    BCrypt::Password.new(self.password_digest).is_password?(input_pass)
  end

  def self.find_by_credentials(user_name, input_pass)
    user = User.find_by_user_name(user_name)

    if user && user.is_password?(input_pass)
      user
    else
      nil
    end
  end

  private
    def ensure_session_token
      self.session_token ||= self.generate_session_token
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  before_action :require_logged_in

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def approve
    current_cat_rental_request.approve!
    redirect_to cat_url(current_cat)
  end

  def create
    @rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @rental_request.save
      redirect_to cat_url(@rental_request.cat)
    else
      flash.now[:errors] = @rental_request.errors.full_messages
      render :new
    end
  end

  def deny
    current_cat_rental_request.deny!
    redirect_to cat_url(current_cat)
  end

  def new
    @rental_request = CatRentalRequest.new
  end

  private
  def current_cat_rental_request
    @rental_request ||=
      CatRentalRequest.includes(:cat).find(params[:id])
  end

  def current_cat
    current_cat_rental_request.cat
  end

  def cat_rental_request_params
    params.require(:cat_rental_request)
      .permit(:cat_id, :end_date, :start_date, :status)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_action :require_logged_in

  def require_logged_in
    redirect_to new_session_url unless logged_in?

  end

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cats_url
    else
      render :new,
      status: :unprocessable_entity
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url
    else
      render :new,
      status: :unprocessable_entity
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def destroy

  end

  private

  def cat_params
    params
      .require(:cat)
      .permit(:name, :birth_date, :sex, :color, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :if_logged_in, only: [:new, :create]

  def if_logged_in
    redirect_to cats_url if logged_in?
  end

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:user_name],
      params[:user][:password]
    )
    if @user.nil?
      render json: "Incorrect username/password"
    else
      # @user.reset_session_token!
      login!(@user)
      redirect_to cats_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :require_sign_in
  before_action :if_logged_in

  def if_logged_in
    redirect_to cats_url if logged_in?
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    # @user.password = params[:password]
    @user.reset_session_token!
    if @user.save
      login!(@user)
      ########## THIS IS REDIRECTED TO CATS!!!!!#######
      redirect_to  cats_url
    else
      render :new,
      status: :unprocessable_entity
    end


  end


  private
    def user_params
      params
        .require(:user)
        .permit(:user_name, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Create Rental Request</h1>

<form action="<%= cat_rental_requests_url %>" method="post">
  <label for="cat_rental_request_cat_id">Cat</label>
  <select name="cat_rental_request[cat_id]"
          id="cat_rental_request_cat_id">
    <option></option>
    <% Cat.all.each do |cat| %>
      <% selected = @rental_request.cat_id == cat.id %>
      <option <%= selected ? "selected" : "" %>
              value="<%= cat.id %>">
        <%= cat.name %>
      </option>
    <% end %>
  </select>
  <br>

  <label for="cat_rental_request_start_date">Start Date</label>
  <input
    type="date"
    name="cat_rental_request[start_date]"
    value="<%= @rental_request.start_date %>"
    id="cat_rental_request_start_date">
  <br>

  <label for="cat_rental_request_end_date">End Date</label>
  <input
    type="date"
    name="cat_rental_request[end_date]"
    value="<%= @rental_request.end_date %>"
    id="cat_rental_request_end_date">
  <br>

  <input type="submit">
</form>

app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(@cat) : cats_url %>
<% form_method = cat.persisted? ? "PATCH" : "POST" %>
<% submit_text = cat.persisted? ? "Update Cat!" : "Create Cat!" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= form_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="cat_name">Cat's Name</label>
  <br>
  <input  name="cat[name]"
          id="cat_name"
          type="text"
          value="<%= @cat.name %>">
  <br><br>

  <label for="cat_birth_date">Cat's Birth Date</label>
  <br>
  <input  name="cat[birth_date]"
          id="cat_birth_date"
          type="date"
          value="<%= @cat.birth_date %>">
  <br><br>

  <label>Sex</label>
  <div>
    <input  name="cat[sex]"
            id="cat_sex_M"
            type="radio"
            value="M"
            <%= @cat.sex == "M" ? "checked" : "" %>>

    <label for="cat_sex_M">Male</label>
    <input name="cat[sex]"
            id="cat_sex_F" type="radio"
            value="F"
            <%= @cat.sex == "F" ? "checked" : "" %>>
    <label for="cat_sex_F">Female</label>
  </div>
  <br>

  <label for="cat_color">Cat color</label>
  <br>

  <select name="cat[color]" id="cat_color">
    <% Cat.colors.each do |color| %>
      <option value="<%= color %>" <%= @cat.color == color ? "selected" : "" %>>
        <%= color.capitalize  %>
      </option>
    <% end %>

  </select>
  <br><br>


  <label for="cat_description">Description</label>
  <br>
  <textarea name="cat[description]" id="cat_description"><%=@cat.description %>
  </textarea>
  <br><br>

  <input type="submit" value="<%= submit_text%>">
</form>


<br><br><br>
<%= link_to "Show me all the cats!", cats_url %>

app/views/cats/_req_tr.html.erb
<tr>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td>
    <% if req.pending? %>
        <%= button_to "Approve", approve_cat_rental_request_url(req) %>
        <%= button_to "Deny", deny_cat_rental_request_url(req) %>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>
</tr>

app/views/cats/edit.html.erb
<h2> Edit Cat </h2>

<%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<h1> Listing of Cats </h1>

<table>
   <% @cats.each do |cat| %>
    <tr>
      <td> <%= cat.name %> </td>
      <td> <%= cat.sex %> </td>
      <td> <%= cat.age %> </td>
      <td> <%= cat.color %> </td>
      <!-- <td> <%= cat.description %> </td> -->
    </tr>
    <% end %>
</table>
<br>
<%= link_to "Create a new cat!", new_cat_url %>

app/views/cats/new.html.erb
<h2> Cat Form! </h2>

<%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<h1> You are currently viewing <%= @cat.name %>'s Profile </h1>

<table>
    <tr>
      <td> <%= @cat.name %> </td>
      <td> <%= @cat.sex %> </td>
      <td> <%= @cat.age %> </td>
      <td> <%= @cat.color %> </td>
    </tr>
</table>

<%= link_to "Edit #{@cat.name}", edit_cat_url(@cat) %>

<h2>Rental Requests</h2>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
  </tr>
  <% @cat.rental_requests.order("start_date").each do |req| %>
    <%= render "req_tr", req: req %>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>

</head>
<body>
  <% if !current_user.nil? %>
    <ul>
      <li>Logged in as: <%= current_user.user_name %></li>
      <li><%= button_to "Logout", session_url, method: :delete %></li>
    </ul>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="_method" value="create">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
    
  <label for="user_user_name">Username</label>
  <input
    type="text"
    name="user[user_name]"
    value="<%= @user.user_name %>"
    id="user_user_name">
  <br>

  <label for="user_password">Password</label>
  <input
    type="text"
    name="user[password]"
    value="<%= @user.password %>"
    id="user_password">
  <br>




  <input type="submit">
</form>